### ISSUE TITLE
ルーティングをする

### ISSUE THREAD

**Issue by coord-e** [Sakuten/frontend#11]
ルーティングをします。想定では`sakuten.org`みたいなドメインを使うので、抽選システムは`/lottery`のような感じになります。
トップページの実装はまだやらなくていいです。(空白or一文)

**Comment by coord-e** [comment]
ルートは、トップページとして別に用意します
/lotteryでログインページ(トップ)
それ以外は任せます

**Comment by anharu2394** [comment]
ログイン後ページも`lottery`ですか？

**Comment by coord-e** [comment]
任せます
`/lottery/login`=>`/lottery/apply`とかでもいいんじゃないかな

**Comment by anharu2394** [comment]
はい。

**Comment by anharu2394** [comment]
https://github.com/alisd23/mobx-react-router を使っていいですか。

**Comment by anharu2394** [comment]
https://github.com/kitze/mobx-router

もありますね。

**Comment by coord-e** [comment]
https://www.npmjs.com/package/mobx-react-router
https://www.npmjs.com/package/mobx-router

npmのDL数的に`mobx-react-router`が良さげです

**Comment by anharu2394** [comment]
わかりました。

**Comment by coord-e** [comment]
Merged. closing
