### ISSUE TITLE
表示させる：repが応募キャンセルしたら各group_memberもキャンセルされる

### ISSUE THREAD

**Issue by shino-sky** [Sakuten/frontend#118]
Step 1: 目的
============

 * [backend #216](https://github.com/Sakuten/backend/pull/216) のプルリクに対応

Step 2: 概要
============

 * `団体応募の代表者キャンセルで、メンバー全員まとめてキャンセル`という旨を表示し、ユーザーに伝える

**Comment by anharu2394** [comment]
@shino-sky これは、キャンセルしようとした時に表示するのですか？

**Comment by shino-sky** [comment]
そんな感じが良いのかなと

**Comment by anharu2394** [comment]
![image](https://user-images.githubusercontent.com/26423094/55678633-ce41c180-5937-11e9-8634-704cfd67d135.png)
キャンセルボタンがないのに、こうなってしまう
