### ISSUE TITLE
Bug: Token失効後リダイレクトが起きない

### ISSUE THREAD

**Issue by Cj-bc** [Sakuten/frontend#20]
`devenv`と`frontend`を最新にして見たのですが、以下のようにUIが夏休みにでも行ってしまったような見た目になりました。
<img width="1425" alt="2018-07-01 18 50 56" src="https://user-images.githubusercontent.com/16875061/42133347-87cbeeac-7d63-11e8-8141-ea240e48b31a.png">

また、鯖再起動後、リダイレクトが起きませんでした。
<img width="1422" alt="2018-07-01 19 22 00" src="https://user-images.githubusercontent.com/16875061/42133387-23d37676-7d64-11e8-826c-05410fff7d1a.png">

仕様ならいいのですがどうなんだろう...?

**Comment by coord-e** [comment]
仕様です
後者対応必須案件なので Sakuten/frontend にIssue立てときますね

**Comment by coord-e** [comment]
ごめんなさい。ここがfrontendだった。

**Comment by Cj-bc** [comment]
あ、了解です
よろしくです
