### ISSUE TITLE
Bug: local:8000へのアクセスでTypeerror

### ISSUE THREAD

**Issue by Cj-bc** [Sakuten/frontend#41]
### Step 1: 環境

 * OS: Darwin crystalslate.local 17.7.0 Darwin Kernel Version 17.7.0: Thu Jun 21 22:53:14 PDT 2018; root:xnu-4570.71.2~1/RELEASE_X86_64 x86_64
 * devenv: b2fd6c55bcfa54dcc300370dd47f20312e03aa84
 * frontend: 2ad68b9b8b2b6dc53bd93f5f5ccb909160094eb5
 * backend: 5104aac9e65643154d59f29446c010e07f4f9bb0

  
#### 再現のための手順:

  1. `devenv`で`./scripts/start.sh`
  2. ブラウザでアクセス
  
#### どうなってしまうか:

  * 以下
<img width="1423" alt="2018-07-17 9 54 03" src="https://user-images.githubusercontent.com/16875061/42790768-b599469a-89a7-11e8-8c59-580319a0132a.png">
<img width="1423" alt="2018-07-17 9 56 46" src="https://user-images.githubusercontent.com/16875061/42790783-c36bc50e-89a7-11e8-983e-01c2a63fba33.png">

  
#### どうなるべきだったのか:

  * エラーが起きず、ログイン画面が出るはずだった
  
#### 関連するコード:

エラー画面で指摘されている場所
* https://github.com/Sakuten/frontend/blob/2ad68b9b8b2b6dc53bd93f5f5ccb909160094eb5 /src/component/ClassroomSelect.js#L7
* https://github.com/Sakuten/frontend/blob/2ad68b9b8b2b6dc53bd93f5f5ccb909160094eb5 /src/store/application.js#L29

**Comment by coord-e** [comment]
これ多分治ってるんですけどどうですか @Cj-bc

**Comment by Cj-bc** [comment]
普通に治ってます大丈夫
close
