### ISSUE TITLE
新仕様対応

### ISSUE THREAD

**Issue by Cj-bc** [Sakuten/frontend#42]
Step 1: 目的
=========

 * [apiの仕様](https://sakuten-api-spec.now.sh/#/v0.1/Authenicate) がガラッと変わりました。ので、それに合わせてフロントもアクセス先を変えていただきたいです
* 対応する必要があるのは、上記URLにて`v0.1`と書かれているもので且つ、`draft`に書かれていないもの。基本的にはできることは増えておらず、APIの位置の訂正等にすぎません。

寝みぃけど字大丈夫時かな

**Comment by coord-e** [comment]
シュッとやります

**Comment by coord-e** [comment]
これ Sakuten/backend#71 が入ってからの方が良さそうな感じがしています。
