### ISSUE TITLE
複数人応募の際の、リクエスト形式を決めて欲しい

### ISSUE THREAD

**Issue by Cj-bc** [Sakuten/frontend#64]
Step 1: 目的
============

 * [backend#37](https://github.com/Sakuten/backend/issues/37)及び[backend#115](https://github.com/Sakuten/backend/issues/115)・[backend#116](https://github.com/Sakuten/backend/issues/116)より、複数人応募の対応が行われます。
 * その際、代表者以外のメンバーの情報をリクエストに含める必要があり、その形式についてbackendと整合性を取る必要があります。

Step 2: 概要
============

 * 今までのリクエスト形式に加え、JSON等で追加情報を含めるようにしてください。
 * 必要な情報は、各メンバーの`secret_id`のみです。
 * 団体の人数は、`secret_id`の配列の長さを見ればいいので含める必要はありません。（但し人数制限の為に、frontでは使うとは思いますが。）
 * こちらの考える例として以下を載せておきます。JSONで返す値が他にない為、`"group_members"`のキーに関してはなくても問題ありません。

```JSON
{
  "group_members": [
    "hogehoge",
    "fugofugo",
    "catiscute"
  ]
}
```

**Comment by coord-e** [comment]
いいんじゃないでしょうか。それで

**Comment by Cj-bc** [comment]
了解です。
では上記の通りのリクエストを期待して書きますね。
`"group_members"`のキーですが、つけるかどうかどうします...?
一応なくてもよくねとは思ってはいる（今後、JSONでリクエストボディーに入れるものを増やさなければ）が、listをそのまま返すのよくないとも見たことが一応あるので 🤔 っていう

**Comment by coord-e** [comment]
つけてください

**Comment by coord-e** [comment]
これからなにかしらリクエストボディに情報を含めることになったときに面倒なので

**Comment by Cj-bc** [comment]
了解です
